package com.hdfc.simulator.HDFCSimulator.model;

public enum StatusENUM {
	
	MOBILE_VERIFICATION_PENDING,
	MOBILE_VERIFICATION_COMPLETE,
	SUSPENSION_REVOKED,
	LOGIN_RETRIES_AVAILABLE,
	LOGIN_SUSPENDED,
	LOGIN_DECLINED,
	EXISTING_CUSTOMER,
	NEW_CUSTOMER,
	NEW_CUSTOMER_GET,
	NEW_CUSTOMER_POST,
	UIDAI_AUTH_FAILED,
	UIDAI_VERIFICATION_COMPLETE,
	PROFILE_IN_PROGRESS,
	PROFILE_COMPLETED,
	ACCOUNT_CREATED,
	FUNDING_AWAITED,
	FUNDING_RECEIVED,
	VKYC_PENDING,
	VKYC_COMPLETE,
	ACTIVATION_PENDING,
	ACCOUNT_ACTIVATED,
	TERMINATED,
	ACCOUNT_REJECTED,
	BLACKLISTED_CUSTOMER,
	WHITELISTED_CUSTOMER,
	ACCOUNT_FAILED, MOBILE_VERIFICATION_FAILED, PROFILE_COMPLETED_GET
	
}
